--- 
- hosts: all
  become: yes
  tasks:
   - name: install git
     dnf:
       name: git
       state: present

   - name: install jenkins  
     dnf: 
      name: 
       - java-11-openjdk
       - jenkins
      state: present
      